---
namespace: telekom_mms
name: ansible_collection_icinga
version: 2.1.0
readme: README.md
authors:
  - Christopher Grau <c.grau@telekom.de>
  - Daniel Uhlmann <daniel.uhlmann@telekom.de>
description: >-
  This collection acts as a 'meta collection' for roles and collections aimed at managing components of Icinga. It also handles Icinga agent installation and custom check rollout.
dependencies:
  telekom_mms.icinga_director: "*"
  telekom_mms.icinga_business_process: "*"
license:
  - GPL-3.0-only
license_file: ""
tags:
  - icinga
  - monitoring
  - agent
  - collection
  - director
  - plugins
repository: https://github.com/telekom-mms/ansible-collection-icinga
documentation: https://github.com/telekom-mms/ansible-collection-icinga
homepage: https://github.com/telekom-mms/ansible-collection-icinga
issues: https://github.com/telekom-mms/ansible-collection-icinga/issues
