namespace: t_systems_mms
name: ansible_collection_icinga
version: 1.1.0
readme: README.md
authors:
  - Christopher Grau <christopher.grau@t-systems.com>
  - Daniel Uhlmann <daniel.uhlmann@t-systems.com>
description: >-
  This collection serves as a kind of 'meta collection' for roles and collections,
  which are used for the configuration and administration of individual components of Icinga.
  Additionally, this collection is used to install
  the Icinga agent and roll out custom checks for every agent.
dependencies:
  t_systems_mms.icinga_director: '*'
  t_systems_mms.icinga_business_process: '*'
license:
  - GPL-3.0-only
license_file: ''
tags:
  - icinga
  - monitoring
  - agent
  - collection
  - director
  - plugins
repository: 'https://github.com/T-Systems-MMS/ansible-collection-icinga'
documentation: 'https://github.com/T-Systems-MMS/ansible-collection-icinga'
homepage: 'https://github.com/T-Systems-MMS/ansible-collection-icinga'
issues: 'https://github.com/T-Systems-MMS/ansible-collection-icinga/issues'
