---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: installed
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: import icinga2 key
      ansible.builtin.rpm_key:
        state: present
        key: "https://packages.icinga.com/icinga.key"
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: install icinga2 repo
      ansible.builtin.yum:
        name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
        state: present
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: install icinga2 basic packages
      apt:
        name: gnupg
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: add icinga2 repo key
      apt_key:
        url: "http://packages.icinga.com/icinga.key"
        state: present
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: add icinga2 repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://packages.icinga.com/debian icinga-bullseye main
        - deb-src http://packages.icinga.com/debian icinga-bullseye main
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: install icinga2 build dependencies
      apt:
        pkg: "icinga2"
        state: "build-dep"
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: install icinga2 basic packages
      apt:
        name: "icinga2"
        state: "present"
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

  collections:
    - t_systems_mms.ansible_collection_icinga

  roles:
    - icinga_agent

  vars:
    icinga_agent_endpoints:
      - name: "icinga2-master1.localdomain"
        host: "192.154.44.101"
      - name: "icinga2-satellite1.localdomain"
        host: "192.154.44.107"
    icinga_agent_zones:
      - name: "master"
        endpoints:
          - "icinga2-master1.localdomain"
      - name: "satellite"
        endpoints:
          - "icinga2-satellite1.localdomain"
        parent: "master"

  post_tasks:
    - name: verify that icinga2.conf exists
      file:
        path: /etc/icinga2/icinga2.conf
        state: file
      register: result_icinga2_conf

    - name: validate icinga2.conf results for RedHat based Distributions
      assert:
        that:
          - "result_icinga2_conf.state == 'file'"
          - "result_icinga2_conf.mode == '0640'"
          - "result_icinga2_conf.owner == 'icinga'"
          - "result_icinga2_conf.group == 'icinga'"
      when: ansible_os_family == 'RedHat'

    - name: validate icinga2.conf results for Debian based Distributions
      assert:
        that:
          - "result_icinga2_conf.state == 'file'"
          - "result_icinga2_conf.mode == '0640'"
          - "result_icinga2_conf.owner == 'nagios'"
          - "result_icinga2_conf.group == 'nagios'"
      when: ansible_os_family == 'Debian'

    - name: verify that constants.conf exists
      file:
        path: /etc/icinga2/constants.conf
        state: file
      register: result_constants_conf

    - name: validate constants.conf results for RedHat based Distributions
      assert:
        that:
          - "result_constants_conf.state == 'file'"
          - "result_constants_conf.mode == '0640'"
          - "result_constants_conf.owner == 'icinga'"
          - "result_constants_conf.group == 'icinga'"
      when: ansible_os_family == 'RedHat'

    - name: validate constants.conf results for Debian based Distributions
      assert:
        that:
          - "result_constants_conf.state == 'file'"
          - "result_constants_conf.mode == '0640'"
          - "result_constants_conf.owner == 'nagios'"
          - "result_constants_conf.group == 'nagios'"
      when: ansible_os_family == 'Debian'

    - name: verify that zones.conf exists
      file:
        path: /etc/icinga2/zones.conf
        state: file
      register: result_zones_conf

    - name: validate zones.conf results for RedHat based Distributions
      assert:
        that:
          - "result_zones_conf.state == 'file'"
          - "result_zones_conf.mode == '0640'"
          - "result_zones_conf.owner == 'icinga'"
          - "result_zones_conf.group == 'icinga'"
      when: ansible_os_family == 'RedHat'

    - name: validate zones.conf results for Debian based Distributions
      assert:
        that:
          - "result_zones_conf.state == 'file'"
          - "result_zones_conf.mode == '0640'"
          - "result_zones_conf.owner == 'nagios'"
          - "result_zones_conf.group == 'nagios'"
      when: ansible_os_family == 'Debian'

    - name: verify that api.conf exists
      file:
        path: /etc/icinga2/features-available/api.conf
        state: file
      register: result_api_conf

    - name: validate api.conf results for RedHat based Distributions
      assert:
        that:
          - "result_api_conf.state == 'file'"
          - "result_api_conf.mode == '0640'"
          - "result_api_conf.owner == 'icinga'"
          - "result_api_conf.group == 'icinga'"
      when: ansible_os_family == 'RedHat'

    - name: validate api.conf results for Debian based Distributions
      assert:
        that:
          - "result_api_conf.state == 'file'"
          - "result_api_conf.mode == '0640'"
          - "result_api_conf.owner == 'nagios'"
          - "result_api_conf.group == 'nagios'"
      when: ansible_os_family == 'Debian'

    - name: verify that icinga2 package is installed
      ansible.builtin.package:
        name: icinga2
        state: present
