---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Install epel repo
      ansible.builtin.yum:
        name: epel-release
        state: installed
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: Import icinga2 key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.icinga.com/icinga.key
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: Install icinga2 repo
      ansible.builtin.yum:
        name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
        state: present
      when: ansible_os_family == 'RedHat'
      tags:
        - molecule-idempotence-notest

    - name: Install icinga2 basic packages
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: Add icinga2 repo key
      ansible.builtin.apt_key:
        url: http://packages.icinga.com/icinga.key
        state: present
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: Add icinga2 repository on debian 11
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://packages.icinga.com/debian icinga-bullseye main
        - deb-src http://packages.icinga.com/debian icinga-bullseye main
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_major_version'] == 11
      tags:
        - molecule-idempotence-notest

    - name: Add icinga2 repository on debian 12
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://packages.icinga.com/debian icinga-bookworm main
        - deb-src http://packages.icinga.com/debian icinga-bookworm main
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_major_version'] == 12
      tags:
        - molecule-idempotence-notest

    - name: Add icinga2 repository on ubuntu 2204
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb http://packages.icinga.com/ubuntu icinga-jammy main
        - deb-src http://packages.icinga.com/ubuntu icinga-jammy main
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"
      tags:
        - molecule-idempotence-notest

    - name: Install icinga2 build dependencies
      ansible.builtin.apt:
        pkg: icinga2
        state: build-dep
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: Install icinga2 basic packages
      ansible.builtin.apt:
        name: icinga2
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

  collections:
    - telekom_mms.ansible_collection_icinga

  roles:
    - icinga_agent

  vars:
    icinga_agent_endpoints:
      - name: icinga2-master1.localdomain
        host: 192.154.44.101
      - name: icinga2-satellite1.localdomain
        host: 192.154.44.107
    icinga_agent_zones:
      - name: master
        endpoints:
          - icinga2-master1.localdomain
      - name: satellite
        endpoints:
          - icinga2-satellite1.localdomain
        parent: master

  post_tasks:
    - name: Verify that icinga2.conf exists
      ansible.builtin.file:
        path: /etc/icinga2/icinga2.conf
        state: file
      register: result_icinga2_conf

    - name: Validate icinga2.conf results for RedHat based Distributions
      ansible.builtin.assert:
        that:
          - result_icinga2_conf.state == 'file'
          - result_icinga2_conf.mode == '0640'
          - result_icinga2_conf.owner == 'icinga'
          - result_icinga2_conf.group == 'icinga'
      when: ansible_os_family == 'RedHat'

    - name: Validate icinga2.conf results for Debian based Distributions
      ansible.builtin.assert:
        that:
          - result_icinga2_conf.state == 'file'
          - result_icinga2_conf.mode == '0640'
          - result_icinga2_conf.owner == 'nagios'
          - result_icinga2_conf.group == 'nagios'
      when: ansible_os_family == 'Debian'

    - name: Verify that constants.conf exists
      ansible.builtin.file:
        path: /etc/icinga2/constants.conf
        state: file
      register: result_constants_conf

    - name: Validate constants.conf results for RedHat based Distributions
      ansible.builtin.assert:
        that:
          - result_constants_conf.state == 'file'
          - result_constants_conf.mode == '0640'
          - result_constants_conf.owner == 'icinga'
          - result_constants_conf.group == 'icinga'
      when: ansible_os_family == 'RedHat'

    - name: Validate constants.conf results for Debian based Distributions
      ansible.builtin.assert:
        that:
          - result_constants_conf.state == 'file'
          - result_constants_conf.mode == '0640'
          - result_constants_conf.owner == 'nagios'
          - result_constants_conf.group == 'nagios'
      when: ansible_os_family == 'Debian'

    - name: Verify that zones.conf exists
      ansible.builtin.file:
        path: /etc/icinga2/zones.conf
        state: file
      register: result_zones_conf

    - name: Validate zones.conf results for RedHat based Distributions
      ansible.builtin.assert:
        that:
          - result_zones_conf.state == 'file'
          - result_zones_conf.mode == '0640'
          - result_zones_conf.owner == 'icinga'
          - result_zones_conf.group == 'icinga'
      when: ansible_os_family == 'RedHat'

    - name: Validate zones.conf results for Debian based Distributions
      ansible.builtin.assert:
        that:
          - result_zones_conf.state == 'file'
          - result_zones_conf.mode == '0640'
          - result_zones_conf.owner == 'nagios'
          - result_zones_conf.group == 'nagios'
      when: ansible_os_family == 'Debian'

    - name: Verify that api.conf exists
      ansible.builtin.file:
        path: /etc/icinga2/features-available/api.conf
        state: file
      register: result_api_conf

    - name: Validate api.conf results for RedHat based Distributions
      ansible.builtin.assert:
        that:
          - result_api_conf.state == 'file'
          - result_api_conf.mode == '0640'
          - result_api_conf.owner == 'icinga'
          - result_api_conf.group == 'icinga'
      when: ansible_os_family == 'RedHat'

    - name: Validate api.conf results for Debian based Distributions
      ansible.builtin.assert:
        that:
          - result_api_conf.state == 'file'
          - result_api_conf.mode == '0640'
          - result_api_conf.owner == 'nagios'
          - result_api_conf.group == 'nagios'
      when: ansible_os_family == 'Debian'

    - name: Verify that icinga2 package is installed
      ansible.builtin.package:
        name: icinga2
        state: present
