---
- name: Add icinga host downtimes
  when: icinga_downtime_host_downtime | bool
  ansible.builtin.uri:
    url: "{{ icinga_downtime_icinga_api_uri }}:{{ icinga_downtime_icinga_api_port }}/v1/actions/schedule-downtime?type=Host"
    url_username: "{{ icinga_downtime_icinga_api_user }}"
    url_password: "{{ icinga_downtime_icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\"",
             "author": "{{ icinga_downtime_author }}",
             "comment": "{{ icinga_downtime_comment }}",
             "start_time": "{{ icinga_downtime_start_time_now }}",
             "end_time": "{{ icinga_downtime_end_time }}",
             "pretty": true,
             "fixed": true,
           }'
  loop:
    - "{{ icinga_downtime_host_filter }}"

- name: Add icinga service downtimes
  when:
    - icinga_downtime_service_downtime | bool
    - icinga_downtime_service_filter == ''
  ansible.builtin.uri:
    url: "{{ icinga_downtime_icinga_api_uri }}:{{ icinga_downtime_icinga_api_port }}/v1/actions/schedule-downtime?type=Service"
    url_username: "{{ icinga_downtime_icinga_api_user }}"
    url_password: "{{ icinga_downtime_icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\"",
             "author": "{{ icinga_downtime_author }}",
             "comment": "{{ icinga_downtime_comment }}",
             "start_time": {{ icinga_downtime_start_time_now }},
             "end_time": {{ icinga_downtime_end_time }},
             "pretty": true,
             "fixed": true,
           }'
  delegate_to: localhost
  loop:
    - "{{ icinga_downtime_host_filter }}"

- name: Add icinga single service downtimes
  when:
    - icinga_downtime_single_service_downtime | bool
    - icinga_downtime_service_filter != ''
  ansible.builtin.uri:
    url: "{{ icinga_downtime_icinga_api_uri }}:{{ icinga_downtime_icinga_api_port }}/v1/actions/schedule-downtime?type=Service"
    url_username: "{{ icinga_downtime_icinga_api_user }}"
    url_password: "{{ icinga_downtime_icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\" && match("*{{ icinga_downtime_service_filter }}*",service.name)",
             "author": "{{ icinga_downtime_author }}",
             "comment": "{{ icinga_downtime_comment }}",
             "start_time": {{ icinga_downtime_start_time_now }},
             "end_time": {{ icinga_downtime_end_time }},
             "pretty": true,
             "fixed": true,
           }'
  delegate_to: localhost
  loop:
    - "{{ icinga_downtime_host_filter }}"
