---
- name: Add icinga host downtimes
  ansible.builtin.uri:
    url: "{{ icinga_api_uri }}:{{ icinga_api_port }}/v1/actions/schedule-downtime?type=Host"
    url_username: "{{ icinga_api_user }}"
    url_password: "{{ icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\"",
             "author": "{{ author }}",
             "comment": "{{ comment }}",
             "start_time": "{{ start_time_now }}",
             "end_time": "{{ end_time }}",
             "pretty": true,
             "fixed": true,
           }'
  loop:
    - "{{ icinga_host_filter }}"
  when:
    - host_downtime

- name: Add icinga service downtimes
  ansible.builtin.uri:
    url: "{{ icinga_api_uri }}:{{ icinga_api_port }}/v1/actions/schedule-downtime?type=Service"
    url_username: "{{ icinga_api_user }}"
    url_password: "{{ icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\"",
             "author": "{{ author }}",
             "comment": "{{ comment }}",
             "start_time": {{ start_time_now }},
             "end_time": {{ end_time }},
             "pretty": true,
             "fixed": true,
           }'
  delegate_to: localhost
  loop:
    - "{{ icinga_host_filter }}"
  when:
    - service_downtime
    - service_filter == ''

- name: Add icinga single service downtimes
  ansible.builtin.uri:
    url: "{{ icinga_api_uri }}:{{ icinga_api_port }}/v1/actions/schedule-downtime?type=Service"
    url_username: "{{ icinga_api_user }}"
    url_password: "{{ icinga_api_password }}"
    validate_certs: true
    method: POST
    status_code: 200
    return_content: true
    headers:
      Accept: application/json
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\" && match(\"*{{ service_filter }}*\",service.name)",
             "author": "{{ author }}",
             "comment": "{{ comment }}",
             "start_time": {{ start_time_now }},
             "end_time": {{ end_time }},
             "pretty": true,
             "fixed": true,
           }'
  delegate_to: localhost
  loop:
    - "{{ icinga_host_filter }}"
  when:
    - single_service_downtime
    - service_filter != ''
