---
- name: Create objects in Icinga
  hosts: localhost
  gather_facts: false
  collections:
    - telekom_mms.icinga_director
  vars:
    object_name: azure_oauth_token
  tasks:
    # icinga_command
    - name: "Icinga_command-{{ object_name }}"
      ansible.builtin.include_role:
        name: "ansible_icinga"
        tasks_from: "icinga_command"
      vars:
        icinga_commands:
          - command_object:
              - "{{ object_name }}"
            command: "{{ object_name }}.py"
            arguments:
              (no key):
                order: 1
                required: true
                skip_key: true
                value: $tenant_id$
              (no key.1):
                order: 2
                required: true
                skip_key: true
                value: $client_id$
              (no key.2):
                order: 3
                required: true
                skip_key: true
                value: $client_secret$
              (no key.3):
                order: 4
                required: true
                skip_key: true
                value: $scope$
    # icinga_service_template
    - name: "Icinga_service_template-{{ object_name }}"
      ansible.builtin.include_role:
        name: "ansible_icinga"
        tasks_from: "icinga_service_template"
      vars:
        icinga_service_templates:
          - service_template_object:
              - "{{ object_name }}"
            check_command: "{{ object_name }}"
            check_interval: 50m

# EXAMPLES
## used for service_apply
# - name: "Icinga_service_apply_azure"
#   include_role:
#     name: "ansible_icinga"
#     tasks_from: "icinga_service_apply"
#   vars:
#     icinga_service_applies:
#     - service_apply_object:
#       - "{{ object_name }}-service_apply"
#       imports: "{{ object_name }}"
#       display_name: "{{ object_name }}"
#       assign_filter: "{{'host.name=\"azure\"'}}"
#       vars:
#         tenant_id: "ID"
#         client_id: "ID"
#         client_secret: "secret"
#         scope: "https://management.azure.com/.default"
