---
- name: Create service template for mms-standard-service and azure REST-API
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
      force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
  tasks:
    - name: Create command Azure REST-API
      telekom_mms.icinga_director.icinga_command:
        state: present
        object_name: check_json_azure_restapi
        command: check_json.pl
        arguments:
          --ignoressl:
            set_if: $json_ignoressl$
          -T: $json_contenttype$
          -a:
            required: true
            value: $json_attributes$
          -b:
            required: true
            type: Function
            body: return get_service(macro("$azure_oauth_token_host$"), macro("$azure_oauth_token_service$")).last_check_result.output
          -c:
            required: true
            type: Function
            body: macro("$json_crit$")
          -d: $json_divisor$
          -e: $json_expect$
          -m: $json_metadata$
          -o: $json_outputvars$
          -p: $json_perfvars$
          -t: $json_timeout$
          -u:
            required: true
            value: $json_url$
          -w:
            required: true
            type: Function
            body: macro("$json_warn$")
          -x: $json_xauth$
