---
- name: Create objects in Icinga
  hosts: localhost
  gather_facts: false
  vars:
    object_name: domon-https
  tasks:
    # icinga_service_template
    - name: "Icinga_service_template-{{ object_name }}"
      ansible.builtin.include_role:
        name: "telekom_mms.icinga_director.ansible_icinga"
        tasks_from: "icinga_service_template"
      vars:
        icinga_service_templates:
          - service_template_object:
              - "domon-standard-service"
            max_check_attempts: "3"
            check_period: "24/7"
            check_interval: "2m"
            retry_interval: "1m"
            enable_notifications: true
            enable_active_checks: true
            enable_passive_checks: false
            enable_event_handler: false
            enable_perfdata: true
            volatile: false
            command_endpoint: null
            vars:
              domon_enabled_notifications: ["mail_24/7"]
          - service_template_object:
              - "{{ object_name }}"
            imports:
              - domon-standard-service
            check_command: http
            check_interval: 300
            vars:
              http_address: $check_address$
              http_extendedperfdata: false
              http_invertregex: false
              http_sni: true
              http_ssl: true
              http_timeout: 30
          - service_template_object:
              - "{{ object_name }}-certificate"
            imports:
              - "{{ object_name }}"
            check_timeout: 60
