---
- name: Create objects in Icinga
  hosts: localhost
  gather_facts: false
  vars:
    object_name: azure_restapi_resourcehealth
  tasks:
    # icinga_service_template
    - name: "Icinga_service_template-{{ object_name }}"
      ansible.builtin.include_role:
        name: "telekom_mms.icinga_director.ansible_icinga"
        tasks_from: "icinga_service_template"
      vars:
        icinga_service_templates:
          - service_template_object:
              - "domon-standard-service"
            max_check_attempts: "3"
            check_period: "24/7"
            check_interval: "2m"
            retry_interval: "1m"
            enable_notifications: true
            enable_active_checks: true
            enable_passive_checks: false
            enable_event_handler: false
            enable_perfdata: true
            volatile: false
            command_endpoint: null
            vars:
              domon_enabled_notifications: [ "mail_24/7" ]
          - service_template_object:
              - domon-json-azure_restapi_resourcehealth
            imports:
              - domon-standard-service
            check_command: check_json_azure_restapi
            check_interval: 5m
            vars:
              json_url:
                "https://management.azure.com/subscriptions/$azure_subscription_id$/resourcegroups/$azure_resource_group$$azure_resource_uri$/\
                providers/Microsoft.ResourceHealth/availabilityStatuses/current?api-version=2020-05-01-preview"
              json_expect: Available
              json_ignoressl: true
              json_attributes: "{properties}->{availabilityState}"
              json_outputvars: "{properties}->{availabilityState},{properties}->{summary},{properties}->{reasonType},{properties}->{occuredTime}"
